homework2 : main.c rtbis.c rtflsp.c rtsec.c rtnewt.c rtsafe.c zbrak.c bessj0.c bessj1.c nrutil.c muller.c nr.h nrutil.h
	cc -o homework2 main.c rtbis.c rtflsp.c rtsec.c rtnewt.c rtsafe.c zbrak.c bessj0.c bessj1.c nrutil.c muller.c -lm
